### ISSUE TITLE
How to turn off the world subrank thing

### ISSUE THREAD

**Issue by CinnaminWolf** [svenar-nl/PowerRanks#11]
![image](https://user-images.githubusercontent.com/71100752/96624190-69ac4480-12da-11eb-96ec-4ffee55ea891.png)
Pee is my world name and I just want to keep my server professional. Pee came in immediately as I downloaded the plugin.

**Comment by svenar-nl** [comment]
To remove the world name edit the fields `chat.format` and `tablist_modification.format` in PowerRanks `config.yml` and remove the `[world]` (`&a[world]&r`) tag from them.

Default chat format `format: '&a[world]&r [usertag] [prefix] [subprefix] [player] [subsuffix] [suffix]&r: [msg]'`
No world name chat format `format: '[usertag] [prefix] [subprefix] [player] [subsuffix] [suffix]&r: [msg]'`

Default tablist format `format: '&a[world]&r [usertag] [prefix] [subprefix] [player] [subsuffix] [suffix]'`
No world name tablist format `format: '[usertag] [prefix] [subprefix] [player] [subsuffix] [suffix]'`

**Comment by CinnaminWolf** [comment]
Thank you, this really helped! <3
