### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ragnar1111** [svenar-nl/PowerRanks#19]
I have this error: https://hastebin.com/nelowihuge.yaml, This is traced back into LWC because the plugin was trying to get the player's groups
which then goes into the vault handler, which it seems PowerRanks does not provide correctly.

**Comment by svenar-nl** [comment]
Thanks for reporting this issue.

The problem has to do with a casting issue.
This has been fixed in commit 4b5525d
It will be available in the next release of PowerRanks (v1.9.3)

**Comment by svenar-nl** [comment]
New version (v1.9.3) is available on [spigotmc](https://www.spigotmc.org/resources/powerranks.64696)
