### ISSUE TITLE
Please use a build system such as Maven or Gradle

### ISSUE THREAD

**Issue by Draycia** [svenar-nl/PowerRanks#2]

**Comment by benwoo1110** [comment]
Yea, I was thinking the same, wanted to build the project but its quite hard without Maven or Gradle. Moving to Maven or Gradle will also allow others to build and in turn creates PR easier. I am willing to open a PR to move it to Maven if you want.

**Comment by svenar-nl** [comment]
You are right. A bluish system like maven or gradle is the way to go. Never got around to do it yet. If @benwoo1110 can create a pull-request that would be great. Otherwise, I will do it myself sometime.

**Comment by benwoo1110** [comment]
I managed to get maven compile running for the legacy version, but DeluxeTags dependency doesn’t have a public maven repo, so you still need that .jar manually downloaded, not sure any better way to do it. Also I am not very sure how you are going about the project structure for v2.0

**Comment by svenar-nl** [comment]
That's great to hear! I've not used Maven before so thank you for helping out.
DeluxeTags is available on [clips-public-repo](http://repo.extendedclip.com/content/repositories/public/) I don't know if this might work?

The v2.0 part is just me trying some things out, it has no "good" structure right now. However, the Legacy is still active and will remain active until v2.0 has gotten to a usable state.

**Comment by benwoo1110** [comment]
Nice, I will take a look at it!
