### ISSUE TITLE
Doesn't work with Multiverse

### ISSUE THREAD

**Issue by Henryws** [svenar-nl/PowerRanks#24]
I don't have any logs or stuff, just want to know why powerranks doesn't work with Multiverse. I filed a bug report on [Multiverse](https://github.com/Multiverse/Multiverse-Core/issues/2531#issue-782942415), and they said it was a problem with Powerranks and it was.

**Comment by GGEZLOLLLLLLLLLLLLLLLLXD** [comment]
Luckperms is the issue, if you have two permission plugins, everything will break. Remove or disable one of them.

**Comment by Henryws** [comment]
Do you mean to remove Luckperms

**Comment by svenar-nl** [comment]
Both, PowerRanks and LuckPerms override Bukkit's internal permission manager, but only one can actually override it. This will result in unpredictable behavior, choose either PR or LP but not both and then test again if the outcome changes.

**Comment by Henryws** [comment]
Does power ranks work like luckperms?

**Comment by svenar-nl** [comment]
Yes, sort of. PowerRanks is like LuckPerms a permission management plugin and achieve similar goals, but in different ways. Both have their advantages and their disadvantages.
I would recommend you to use PowerRanks, but that is kinda a biased recommendation :P

**Comment by Henryws** [comment]
I've tried PowerRanks on my server and the performance tanked. Sorry but LuckPerms just has better performance for me
