### ISSUE TITLE
Cant set permissions for any roles on 1.7.9 v3.5 bukkit version

### ISSUE THREAD

**Issue by tomutar78253** [svenar-nl/PowerRanks#25]
If you can send me some kind of guide for that version it would be great

**Comment by gamergeek1213** [comment]
same here i use lucky perms and it seems like no one can use any commands due to no having perms. i know ive set up luckyperms properly. any idea how to fix?

**Comment by TeamArty** [comment]
> same here i use lucky perms and it seems like no one can use any commands due to no having perms. i know ive set up luckyperms properly. any idea how to fix?

Do you use powerranks and lucky perms together?

**Comment by gamergeek1213** [comment]
I do. does it conflict?

**Comment by svenar-nl** [comment]
PowerRanks and LuckPerms should not be used alongside each other, because that will result in unexpected behavior.
Both register as a permissions handler and try to override each other.
Choose either PowerRanks or LuckPerms. But not both.

**Comment by TeamArty** [comment]
Yes it does, pr and lp both use bukkit permissions and when you use them together bad stuff happens like that

**Comment by gamergeek1213** [comment]
oh alright thx
