### ISSUE TITLE
Commands output with an internal server error

### ISSUE THREAD

**Issue by OrangeTurtle197** [svenar-nl/PowerRanks#27]
**I'm not a dummy, so I've checked these**
- [y] I am not using any other permission management plugin
- [y] I use the latest available version of PowerRanks
- [y] I am a human

**Describe the bug**
Commands output with an internal server error rather than completing successfully

**To Reproduce**
1. Start a PaperMC 1.16.5 server and install PowerRanks
2. Join the server and make yourself an operator
3. Attempt to use a command (example: `/powerranks gui`)

**Expected behavior**
The command to complete (e.g. a GUI to appear to configure PowerRanks)

**Screenshots**
https://turtlecraft.page.link/qAZp

**Logs**
https://turtlecraft.page.link/M5zM

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro for Workstations (Version 20H2, Build 19042.804)
 - Server type PaperMC version git-Paper-436 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
 - Minecraft Version 1.16.5
 - PowerRanks version 1.9.7
 - Server and client are running on the same machine

**Additional context**
N/A

If you see German, it's because I'm messing around with Minecraft languages.

**Comment by svenar-nl** [comment]
Please create a backup of your *config.yml* file and remove it from */plugins/PowerRanks*.
Then restart your server.
Due to an bug in v1.9.7 the config file fails to update, this will be resolved in the next version.
Please close the issue if this resolves the issue

**Comment by NenoxxLegit** [comment]
Hello, when i type "pr" and than any of commands the plugin countains for example "/pr setownrank Owner" in the chat box appears message that something with this plugin is not right. 
Can u tell me what is the problem or fix it?

**Comment by OrangeTurtle197** [comment]
> Hello, when i type "pr" and than any of commands the plugin countains for example "/pr setownrank Owner" in the chat box appears message that something with this plugin is not right.
> Can u tell me what is the problem or fix it?

@NenoxxLegit try deleting any references (config settings, main jar plugin, etc) and re-download the mod, then put it back in the plugins folder
