### ISSUE TITLE
no rank showing up for random reason

### ISSUE THREAD

**Issue by ItzEnderArkail** [svenar-nl/PowerRanks#38]
server version: 1.16.5 purpur
plugin version: 1.9.9R3

Happend for some random reason idk why
bug:
[17:08:22 WARN]: [PowerRanks] Task #6 for PowerRanks v1.9.9R3 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Long.intValue()" because the return value of "nl.svenar.PowerRanks.Cache.CachedPlayers.getLong(String)" is null
        at nl.svenar.PowerRanks.PowerRanks.updatePlaytime(PowerRanks.java:952) ~[?:?]
        at nl.svenar.PowerRanks.PowerRanks$3.run(PowerRanks.java:355) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]

**Comment by greatericontop** [comment]
Send the ranks.yml, config.yml, and plugin list please

**Comment by ItzEnderArkail** [comment]
config.yml

general:
  disable-op: false
  playtime-update-interval: 5
chat:
  enabled: true
  format: '&r %clans_clan_tag% [prefix] [subprefix] [player] [subsuffix] [suffix]&r:
    [msg]'
tablist_modification:
  enabled: true
  format: '&r %clans_clan_tag% [prefix] [subprefix] [player] [subsuffix] [suffix]'
nametagedit:
  prefix: '[usertag] [prefix] [subprefix]'
  suffix: '[subsuffix] [suffix]'
signs:
  enabled: true
  title_format: '&0[&b%plugin_name%&0]'
plugin_hook:
  vault_economy: true
  vault_permissions: true
  placeholderapi: true
  deluxetags: false
  nametagedit: true
announcements:
  rankup:
    enabled: false
    format: '[powerranks_prefix] &6[player]''s rank has been changed to [rank]'
  promote:
    enabled: false
    format: '[powerranks_prefix] &6[player] has been promoted to [rank]'
  demote:
    enabled: false
    format: '[powerranks_prefix] &6[player] has been demoted to [rank]'
updates:
  enable_update_checking: true
  automatic_download_updates: false
  automatic_update_config_files: true
addon_manager:
  accepted_terms: false
rankup:
  buy_command:
    enabled: false
    command: say %playername% just bought the rank %rankname%
version: 1.9.93

ranks.yml
Default: Member
Usertags: ''
Groups:
  Member:
    permissions:
    - essentials.back
    - essentials.back.into.world
    - essentials.back.into.spawn
    - essentials.afk
    - essentials.afk.auto
    - essentials.balance
    - essentials.balance.others
    - essentials.exp
    - essentials.home.bed
    - essentials.list
    - essentials.motd
    - essentials.msg
    - essentials.msgtoggle
    - essentials.pay
    - essentials.payconfirmtoggle
    - essentials.paytoggle
    - essentials.rtoggle
    - essentials.sethome
    - essentials.sethome.bed
    - essentials.showkit
    - essentials.time
    - essentials.tpa
    - essentials.tpacancel
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.warp
    - essentials.warp.list
    - essentials.tptoggle
    - essentials.spawn
    - essentials.back.onteleport
    - essentials.back.ondeath
    - essentials.suicide
    - essentials.back.into.DIM1
    - essentials.back.into.DIM-1
    - essentials.info
    - clans.create
    - clans.invite
    - clans.accept
    - clans.kick
    - clans.stats
    - clans.topstats
    - clans.base
    - clans.setbase
    - clans.leave
    - clans.delete
    - clans.list
    - auctionhouse.cancel
    - auctionhouse.use
    - auctionhouse.menu
    - auctionhouse.search
    - auctionhouse.help
    - auctionhouse.sell
    - auctionhouse.list
    - auctionhouse.ulist
    - auctionhouse.selling
    - auctionhouse.sold
    - auctionhouse.expired
    - auctionhouse.return
    - auctionhouse.auctions.5
    - protectionstones.create
    - protectionstones.get
    - protectionstones.destroy
    - protectionstones.merge
    - protectionstones.unclaim
    - protectionstones.view
    - protectionstones.info
    - protectionstones.info.others
    - protectionstones.count
    - protectionstones.list
    - protectionstones.home
    - protectionstones.sethome
    - protectionstones.name
    - protectionstones.owners
    - protectionstones.members
    - protectionstones.flags
    - protectionstones.buysell
    - protectionstones.limit.4
    - skinsrestorer.command
    - skinsrestorer.command.set
    - skinsrestorer.command.gui
    - skinsrestorer.command.clear
    - skinsrestorer.command.update
    - trade.player
    - tradesystem.trade.initiate
    - tradesystem.trade
    - clans.chat
    - clans.togglechat
    - clans.show
    - essentials.balancetop
    - essentials.rules
    - betterrtp.use
    - betterrtp.world.world
    - essentials.home
    - jobs.use
    - goldencrates.user
    - essentials.back.into.world_the_end
    - essentials.back.into.world_nether
    - essentials.back.into.Spawn
    - playerkits.kit.inicial
    - betterrtp.world
    inheritance: []
    chat:
      prefix: '&3Miembro &8➤'
      suffix: ''
      chatColor: '&f'
      nameColor: '&f'
    level:
      promote: ''
      demote: ''
    economy:
      buyable: []
      cost: 0
      description: ''
    gui:
      icon: stick
  Moderator:
    permissions:
    - essentials.ban
    - essentials.ban.exempt
    - essentials.unban
    - essentials.tempban
    - essentials.ban.notify
    - essentials.banip.notify
    - essentials.afk.kickexempt
    - essentials.kick
    - essentials.kick.exempt
    - essentials.kick.notify
    - essentials.kickall.exempt
    - essentials.tp
    - essentials.tp.others
    - essentials.tpoffline
    - essentials.tpo
    - essentials.tptoggle
    - essentials.socialspy
    - essentials.vanish
    - essentials.silentjoin.vanish
    - essentials.gamemode.spectator
    - essentials.gamemode.survival
    - essentials.gamemode
    - essentials.fly
    - essentials.speed.fly
    - essentials.speed
    - essentials.nick
    - essentials.nick.color
    - essentials.nick.format
    - fakelogin.fakejoin
    - fakelogin.fakeleave
    inheritance:
    - Member
    - Vip
    chat:
      prefix: '&6Mod &8➤'
      suffix: ''
      chatColor: '&b'
      nameColor: '&f'
    level:
      promote: Admin
      demote: ''
    economy:
      buyable: []
      cost: 0
      description: ''
    gui:
      icon: stone
  Admin:
    permissions:
    - '*'
    inheritance: []
    chat:
      prefix: '&aAdmin &8➤'
      suffix: ''
      chatColor: '&b'
      nameColor: '&f'
    level:
      promote: Owner
      demote: Moderator
    economy:
      buyable: []
      cost: 0
      description: ''
    gui:
      icon: redstone
  Owner:
    permissions:
    - '*'
    - enchantmentsolution.command.enchant
    - essentials.silentjoin
    - essentials.silentquit
    inheritance: []
    chat:
      prefix: '&cDueño &8➤'
      suffix: ''
      chatColor: '&b'
      nameColor: '&f'
    level:
      promote: ''
      demote: Admin
    economy:
      buyable: []
      cost: 0
      description: ''
    gui:
      icon: diamond
  Vip:
    permissions:
    - tim.vip
    - playerkits.kit.vip
    - playerkits.kit.dailykey
    - essentials.nick
    - essentials.rgb
    - essentials.nick.color
    - essentials.teleport.cooldown.bypass.back
    - essentials.teleport.cooldown.bypass.tpa
    - skinsrestorer.bypasscooldown
    - essentials.enderchest
    - essentials.recipe
    - essentials.smithingtable
    - essentials.cartographytable
    - essentials.craft
    - betterrtp.biome
    - essentials.hat
    - essentials.me
    - essentials.msg.color
    - essentials.msg.rgb
    - essentials.signs.color
    - essentials.signs.rgb
    - essentials.signs.magic
    - essentials.chat.color
    - auctionhouse.auctions.20
    - protectionstones.limit.10
    - essentials.grindstone
    - essentials.loom
    - essentials.stonecutter
    - essentials.anvil
    inheritance:
    - Member
    chat:
      prefix: '&2Vip &8➤'
      suffix: ''
      chatColor: '&f'
      nameColor: '&f'
    level:
      promote: ''
      demote: ''
    economy:
      buyable: []
      cost: 0
    gui:
      icon: stone
  'null':
    permissions: []
    inheritance: []
version: 1.9.93

**I can't send the files so i send all the text**
