### ISSUE TITLE
RGB colour support

### ISSUE THREAD

**Issue by benwoo1110** [svenar-nl/PowerRanks#4]
**FEATURE**
Minecraft 1.16 came with support for hex codes, It would be great if PowerRanks support it too!

**Comment by svenar-nl** [comment]
Thanks for the suggestion.
It will be implemented in the next version of PowerRanks.
![PowerRanks_RGB](https://user-images.githubusercontent.com/11473832/93741192-39df2380-fbec-11ea-9dd6-4a09bd2a79cc.png)
