### ISSUE TITLE
Need Help to remove world name in chat prefix!

### ISSUE THREAD

**Issue by TheKrunchyKen** [svenar-nl/PowerRanks#42]
![Screenshot (236)](https://user-images.githubusercontent.com/94597352/142370396-3d55c8bd-1595-46f6-9481-bb37524ab597.png)
I need help with the world name next to the owner role i don't know how to disable it.

**Comment by svenar-nl** [comment]
Execute ‘/pr config removeworldtag’ to remove the world name.
