### ISSUE TITLE
PremiumVanish chat blocker is glitched

### ISSUE THREAD

**Issue by 10Meisterbaelle** [svenar-nl/PowerRanks#43]
PremiumVanish by default blocks chat while you are in vanish unless you put a / after your message, but if you do that, the / is not supposed to be sent with the message but the PowerRanks chat formats still show it.

**Comment by svenar-nl** [comment]
Added workaround in commit.
[52a846c](https://github.com/svenar-nl/PowerRanks/commit/52a846c265ab74496d1412dbd14965022071a468)

In general I do not add support for any premium plugins and a proper fix won't be implemented.
