### ISSUE TITLE
Tablist requrires /pr reload all to register changes

### ISSUE THREAD

**Issue by bop34** [svenar-nl/PowerRanks#5]
**I'm not a dummy, so I've checked these**
- [Y] I am not using any other permission management plugin
- [Y] I use the latest available version of PowerRanks
- [Y] I am a human

**Describe the bug**
When altering the tablist in the config, `/pr reload all` is needed instead of `/pr reload config`. It should be the latter as it is a config change.

**To Reproduce**
1. Join the server
2. View the tablist
3. Change the `tablist_modification` format in config.yml
4. Type `/pr reload config` in the chat
5. View the tablist. It is the same as before
6. Type  `/pr reload all`
7. The tablist now changes
**Expected behavior**
Any changes to the tablist config should be shown.

**Comment by svenar-nl** [comment]
Thanks for reporting this issue.

I can confirm that this indeed is an issue and I will fix this for the next version of PowerRanks (v1.8)
