### ISSUE TITLE
Web editor cannot apply subranks

### ISSUE THREAD

**Issue by taterhatr** [svenar-nl/PowerRanks#6]
When I try to apply a subrank on a player then export the config to my server, it does not apply
**To Reproduce**
1. /pr webeditor start
2. Create a rank
3. Apply the subrank on a player
4. Export and /pr reload all

**Expected behavior**
The rank will not apply

**Screenshots**

**Logs**
If applicable, post log files from your server

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Server type: Paper
 - Minecraft Version: 1.16.3
 - PowerRanks version: Latest

**Comment by svenar-nl** [comment]
Thanks for reporting this issue.

I see what's happening here.
I've create a test rank in the web editor and applied that as a sub-rank to myself, then exported it to the server. After checking I can see the sub-rank being there. But a reload or restart of the server removes it.
`subranks={TestRank={use_prefix=true, use_suffix=true, use_permissions=true, worlds=[All]}}`
When PowerRanks shuts down or restarts it writes the cached files back to the file-system, overwriting the current Players.yml and thus overwrites the sub-ranks that have been configured from the web editor.

I've updated the PowerRanksWebEditor add-on and that is now available for download on https://powerrankseditor.svenar.nl
This new version of the add-n (v1.2) fixes this issue.
