### ISSUE TITLE
Entire Prefix Dissappears including the vanilla minecraft one when you have a rank and delete it.

### ISSUE THREAD

**Issue by Yeetster-cmd** [svenar-nl/PowerRanks#9]
**I'm not a dummy, so I've checked these**
- [ ] I am not using any other permission management plugin
- [ ] I use the latest available version of PowerRanks
- [ ] I am a human

**Describe the bug**
Entire Prefix Dissappears including the vanilla minecraft one when you have a rank and delete it.

**To Reproduce**
1. Create a rank
2. Set it as your rank
3. Delete the rank
4. Type in chat
5.Entire Prefix is gone, including the vanilla prefix "<>"

**Expected behavior**
It should 1.not remove the vanilla prefix or 2.give you the default rank

**Desktop (please complete the following information):**
 - OS: [Linux 3.1 (idk)]
 - Server type [Paper]
 - Minecraft Version [1.16.2]
 - PowerRanks version [e.g. 1.8]

**Comment by svenar-nl** [comment]
Thanks for reporting that issue.
This is indeed a problem that I overlooked and I will fix it for the next version.

https://github.com/svenar-nl/PowerRanks/blob/e20ca8986f0ce0be13e3546b0fcf6a5d3f56dbeb/Legacy/PowerRanks/src/nl/svenar/PowerRanks/Data/Users.java#L544
